---
php_version: 8.1
php_packages:
  - php{{ php_version }}-fpm
  - php{{ php_version }}-mysql
  - php{{ php_version }}-xml
  - php{{ php_version }}-gd
  - php{{ php_version }}-curl
  - php{{ php_version }}-mbstring
  - php{{ php_version }}-imagick
  - php{{ php_version }}-zip
